image: Visual Studio 2015

environment:
  COVERALLS_REPO_TOKEN:
    secure: 6MvLG18tMc0654Hpv1jt00lP2xwaCmjQQ0b0xbW//EjbjKF8Su+XxCuds/GqSrTU
  MYGET_API_TOKEN:
    secure: AkVuHBLFZISuM+BYCrFiUEroGNmUViLXBoty1WD5+UbD+oo3/n0W6ojRshtLY3sD

shallow_clone: false

build: off
test: off
deploy: off

branches:
  only:
    - master
    - /^testing.*/

build_script:
- ps: .\build.ps1 -Target AppVeyor -Configuration Debug
