site_name: Cake.Paket
repo_url: https://github.com/larzw/Cake.Paket
docs_dir: Documentation
pages:
    - 'Introduction': 'index.md'
    - 'Cake.Paket.Module': 'Cake.Paket.Module.md'
    - 'Cake.Paket': 'Cake.Paket.md'
    - 'Cake Bootstrapper': 'CakeBootstrapper.md'
    - 'Maintainers': 'Maintainers.md'
